export const GET_CONTACTS_ATTEMPT = "GET_CONTACTS_ATTEMPT";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const SIGNUP_ATTEMPT = "SIGNUP_ATTEMPT";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const SIGNIN_ATTEMPT = "SIGNIN_ATTEMPT";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";

export const CHECK_USER_ATTEMPT = "CHECK_USER_ATTEMPT";
export const CHECK_USER_SUCCESS = "CHECK_USER_SUCCESS";
export const CHECK_USER_FAIL = "CHECK_USER_FAIL";

export const LOGOUT_ATTEMPT = "LOGOUT_ATTEMPT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const ADD_CONTACT = "ADD_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const SELECT_CONTACT_FAIL = "SELECT_CONTACT_FAIL";
